## scripts: examples/digit_rgb_to_cloud.py

### user set options ###

setup: sim # sim, real

## sim dataset shapes: cube, sphere, toy_brick, toy_human
dataset_names: ['tacto/cube/dataset_0000/', 'tacto/cube/dataset_0001/']

## real dataset shapes: sphere, pyramid
# dataset_names: ['real/sphere/digit-0.5mm-ball-bearing-zup_2021-08-31-21-37-35']
# dataset_names: ['real/pyramid/digit-flatcorner_2021-09-10-21-13-17']

max_depth: 0.0198 # max depth value (close to avg gel depth)
remove_background_depth: True # sets depth>max_depth to 0 which is filtered out in points3d

use_gt_normals: False # only for sim data

visualize:
  imgs: True
  cloud: True

########################

random_seed: 0
datatype: test

dataloader:  
  batch_size: 1 
  shuffle: False
  num_workers: 8

pix2pix:
  model_name: sim_sphere_sim_cube_real_sphere
  model_type: pix2pix
  direction: AtoB
  dataset_mode: aligned
  netG: unet_256

  debug_vis: False

sensor:
  mesh_name: digit.STL

  T_cam_offset_sim: [[2.22e-16, 2.22e-16, -1.00e+00, 0.00e+00],
                [-1.00e+00, 0.00e+00, -2.22e-16, 0.00e+00], 
                [0.00e+00, 1.00e+00, 2.22e-16, 1.50e-02],
                [0.00e+00, 0.00e+00, 0.00e+00, 1.00e+00]]

  # rotation of +90 degrees about x-axis
  T_cam_offset_real: [[1., 0., 0., 0.],
                [0., 0., -1, 0.],
                [0., 1., 0., 0.],
                [0., 0., 0., 1.]]

  P:  [[2.30940108e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.73205081e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, -1.04081633e+00, -2.04081633e-03],
       [0.00000000e+00, 0.00000000e+00, -1.00000000e+00, 0.00000000e+00]]
  
  z_near: 0.001
  z_far: 0.05

  # gel min depth: 0.01910434
  gel_depth_map_loc: local/resources/gel_depth_map.csv
  gel_depth_offset: 1e-4

  gel_width: 0.02 # gel width (y-axis) in meters
  gel_height: 0.03 # gel height (x-axis) in meters